name = "AMDGPU"
uuid = "21141c5a-9bdb-4563-92ae-f87d6854732e"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>", "Valentin Churavy <v.churavy@gmail.com>", "Anton Smirnov <tonysmn97@gmail.com>"]
version = "0.9.6"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
HIP_jll = "2696aab5-0948-5276-aa9a-2a86a37016b8"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LLD_jll = "d55e3150-da41-5e91-b323-ecfd1eec6109"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
LLVM_jll = "86de99a1-58d6-5da7-8064-bd56ce2e322c"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ROCmDeviceLibs_jll = "873c0968-716b-5aa7-bb8d-d1e2e2aeff2d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnsafeAtomicsLLVM = "d80eeb9a-aca5-4d75-85e5-170c8b632249"
hsa_rocr_jll = "dd59ff1a-a01a-568d-8b29-0669330f116a"

[compat]
AbstractFFTs = "1.0"
Adapt = "4"
Atomix = "0.1"
CEnum = "0.4, 0.5"
ExprTools = "0.1"
GPUArrays = "10"
GPUCompiler = "0.26.5"
HIP_jll = "5.4"
KernelAbstractions = "0.9.2"
LLD_jll = "14, 15, 16"
LLVM = "7"
LLVM_jll = "14, 15, 16"
Preferences = "1"
PrettyTables = "2"
ROCmDeviceLibs_jll = "5.6.1"
Random123 = "1.6"
RandomNumbers = "1.5"
SpecialFunctions = "2"
StaticArraysCore = "1"
UnsafeAtomicsLLVM = "0.1"
hsa_rocr_jll = "5.4"
julia = "1.9"
