name = "AMDGPUnative"
uuid = "12f4821f-d7ee-5ba6-b76b-566925c5fcc5"
version = "0.1.1"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HSARuntime = "2c364e2c-59fb-59c3-96f3-194112e690e0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Adapt = "0.4, 1.0"
BinaryProvider = "0.5"
DataStructures = "0.15, 0.16, 0.17"
HSARuntime = "0.2.6"
LLVM = "1.3"
TimerOutputs = "0.5"
julia = "1"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SpecialFunctions", "Test"]
