name = "AMDGPU"
uuid = "21141c5a-9bdb-4563-92ae-f87d6854732e"
authors = ["Julian P Samaroo <jpsamaroo@jpsamaroo.me>", "Valentin Churavy <v.churavy@gmail.com>"]
version = "0.2.17"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
ExprTools = "e2ba6199-217a-4e67-a87a-7c52f15ade04"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"
HIP_jll = "2696aab5-0948-5276-aa9a-2a86a37016b8"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ROCmDeviceLibs_jll = "873c0968-716b-5aa7-bb8d-d1e2e2aeff2d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
hsa_rocr_jll = "dd59ff1a-a01a-568d-8b29-0669330f116a"
rocRAND_jll = "a6151927-a32b-54c0-bc8c-bbd7b3f1a996"

[compat]
AbstractFFTs = "0.5, 1.0"
Adapt = "3.0"
BinaryProvider = "0.5"
CEnum = "0.2, 0.3, 0.4"
ExprTools = "0.1"
GPUArrays = "6, 7, 8"
GPUCompiler = "0.12, 0.13"
HIP_jll = "4.2"
LLVM = "4.6"
MacroTools = "0.5"
ROCmDeviceLibs_jll = "4.2"
Requires = "1"
SpecialFunctions = "1, 2"
Setfield = "0.5, 0.6, 0.7"
hsa_rocr_jll = "4.2"
julia = "1.7"
rocRAND_jll = "4.2"
