[general]
library_name = "librocsolver"
output_file_path = "../src/solver/librocsolver.jl"
export_symbol_prefixes = []
print_using_CEnum = false
output_ignorelist = [
    "ROCSOLVER_DEPRECATED_EXPORT",
    "ROCSOLVER_DEPRECATED_NO_EXPORT",
    "ROCSOLVER_VERSION_TWEAK",
]

[codegen]
use_ccall_macro = true
