[general]
library_name = "librocfft"
output_file_path = "../src/fft/librocfft.jl"
export_symbol_prefixes = []
print_using_CEnum = false
output_ignorelist = [
    "ROCFFT_DEPRECATED_EXPORT",
    "ROCFFT_DEPRECATED_NO_EXPORT",
    "rocfft_version_tweak",
]

[codegen]
use_ccall_macro = true
