[general]
library_name = "libMIOpen_path"
output_file_path = "../src/dnn/libMIOpen.jl"
export_symbol_prefixes = []
output_ignorelist = [
    "miopenAcceleratorQueue_t",
    "MIOPEN_DEPRECATED_EXPORT",
    "MIOPEN_DEPRECATED_NO_EXPORT",
    "MIOPEN_INTERNALS_DEPRECATED_EXPORT",
    "MIOPEN_INTERNALS_DEPRECATED_NO_EXPORT",
    "MIOPEN_VERSION_TWEAK",
    "MIOPEN_USE_GEMM",
    "MIOPEN_INSTALLABLE",
]

[codegen]
use_ccall_macro = true
