[general]
library_name = "libhip"
output_file_path = "../src/hip/libhip.jl"
output_ignorelist = [
    "__HOST_DEVICE__",
    "HIP_DEPRECATED_MSG",
]

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true
